apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicea
  namespace: microservices-demo
  labels:
    app: servicea
spec:
  replicas: 3
  selector:
    matchLabels:
      app: servicea
  template:
    metadata:
      labels:
        app: servicea
    spec:
      containers:
      - name: servicea
        image: quixpublic.azurecr.io/servicea:new
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:80"
        - name: OTEL_SERVICE_NAME
          value: "ServiceA"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector-opentelemetry-collector.observability.svc.cluster.local:4318"
        - name: ALLOWED_ORIGINS
          value: "*"
        - name: SERVICEB_URL
          value: "http://serviceb.microservices-demo.svc.cluster.local"
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: servicea
  namespace: microservices-demo
  labels:
    app: servicea
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: servicea 